import type { Command } from "commander";
import { AztecAddress } from "@aztec/aztec.js/addresses";
import { Fr } from "@aztec/aztec.js/fields";
import { OrderbookContract } from "../../../tests/integration/generated/Orderbook.js";
import { AggregatorRegistryContract } from "../../../tests/integration/generated/AggregatorRegistry.js";
import { loadConfig } from "../config.js";
import { openCli } from "../wallet.js";
import { randomField } from "../field.js";
import { broadcastReveal, type RevealPayload } from "../reveal.js";
import { parsePath } from "../path.js";

export function registerOrder(program: Command): void {
  program
    .command("order")
    .description("submit a private order")
    .requiredOption("--side <buy|sell>", "buy = deposit tUSDC, sell = deposit tETH")
    .requiredOption("--amount <n>", "input amount in the token's smallest unit")
    .requiredOption("--limit <price>", "limit price, Q-format scaled to 1e18")
    .option("--path <comma-list>", "Token path, e.g. 'tUSDC,tETH' or 'tUSDC,tETH,tBTC'", "tUSDC,tETH")
    .action(async (_opts, cmd: Command) => {
      const opts = cmd.optsWithGlobals();
      const side = String(opts.side).toLowerCase();
      if (side !== "buy" && side !== "sell") {
        throw new Error(`--side must be "buy" or "sell", got "${opts.side}"`);
      }
      const sideFlag = side === "sell"; // false = bid (tUSDC), true = ask (tETH)
      const amount = BigInt(opts.amount);
      const limit = BigInt(opts.limit);

      const config = loadConfig(opts.config);
      const ctx = await openCli(config, Number(opts.account));
      try {
        const orderbook = await OrderbookContract.at(
          AztecAddress.fromString(config.orderbook),
          ctx.wallet,
        );
        const orderNonce = randomField();
        // Sub-4: resolve --path option against config-driven alias map.
        // tBTC is optional — only present in Sub-4+ deploys.
        const aliases: Record<string, string> = {
          tUSDC: config.tUSDC,
          tETH: config.tETH,
          ...(config.tBTC ? { tBTC: config.tBTC } : {}),
        };
        const { path_len, path } = parsePath(opts.path as string, aliases);
        const pathFields: [Fr, Fr, Fr] = [
          Fr.fromString(path[0]),
          Fr.fromString(path[1]),
          Fr.fromString(path[2]),
        ];
        // Cast to `any` to bridge the stale generated type (5 args) and the
        // actual Noir signature added in Sub-4 (7 args: +path_len, +path).
        // The generated Orderbook.ts is gitignored and will be regenerated by
        // `pnpm codegen` once the contracts are recompiled with Docker.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const tx = await (orderbook.methods.submit_order as any)(
          sideFlag, amount, limit, randomField(), orderNonce,
          BigInt(path_len), pathFields)
          .send({ from: ctx.account });
        const receipt: unknown = await (tx as { wait?: () => Promise<unknown> }).wait?.();

        console.log(`order submitted (${side}, amount ${amount}, limit ${limit})`);
        console.log(`order nonce: 0x${orderNonce.toString(16)}`);
        console.log(`cancel later with: zswap cancel --nonce 0x${orderNonce.toString(16)}`);

        // Sub-3: broadcast reveal to all bonded aggregators. Best-effort; if the
        // aggregator registry isn't deployed yet (Sub-1 MVP config), skip silently.
        if (!config.aggregatorRegistry) {
          return;
        }
        try {
          const epochSim = await orderbook.methods.get_epoch().simulate({ from: ctx.account });
          const epoch = (epochSim as { result: { epoch_id: bigint } }).result;
          const epochId = Number(epoch.epoch_id);
          // submitted_at_block: best-guess from the receipt (if available) or 0.
          // The aggregator daemon's validateReveals will reject if this doesn't
          // fold to the on-chain order_acc, so a wrong guess just costs the
          // submitter a re-broadcast.
          const blockNum =
            (receipt as { blockNumber?: bigint | number })?.blockNumber ?? 0;
          const payload: RevealPayload = {
            epoch_id: epochId,
            order_nonce: new Fr(orderNonce).toString(),
            side: sideFlag,
            amount_in: amount.toString(),
            limit_price: limit.toString(),
            submitted_at_block: Number(blockNum),
            owner: ctx.account.toString(),
          };
          const registry = await AggregatorRegistryContract.at(
            AztecAddress.fromString(config.aggregatorRegistry),
            ctx.wallet,
          );
          const result = await broadcastReveal(payload, registry, ctx.account);
          console.log(
            `reveal broadcast: ${result.pushed} aggregators reached, ${result.skipped} unreachable`,
          );
        } catch (e) {
          console.warn(`reveal broadcast failed: ${(e as Error).message}`);
        }
      } finally {
        await ctx.stop();
      }
    });
}
